### PR TITLE
Demzne 1238 add a pending custodians airgap between elections

### PR DESCRIPTION
**Pull request by angelol**

### CODE REVIEW

**Comment by dskvr** [comment]
Task linked: [DEMZNE-1238 Add a pending custodians airgap between elections](https://app.clickup.com/t/18330827/DEMZNE-1238)

**Review by dallasjohnson — APPROVED** [review]
Does this handle the first week case where the current custodians should stay in power if the pending custodians is empty?
LGTM otherwise.

**Comment by angelol** [comment]
That's what I thought the code does. But you question made me suspicious. I went ahead and added a test case for this specifically and turns out it didn't handle it correctly. Code is fixed so this case is handled correctly as well. All tests are passing now.

**Comment by dallasjohnson** [comment]
When you raised the question yesterday, I realised, although I had thought about it I had not handled that case in the code. Thanks for the change.

**Review by dallasjohnson — APPROVED** [review]
LGTM 👍 Thanks

**Pull request merged**
